### PR TITLE
Fix action to work with Resharper version 2024.x

### PR DESCRIPTION
**Pull request by Summonair**
Hey, i started implementation of SARIF support for 2024.x version of resharper,
its really hard to run this project locally, is there an easy way to do it? 
(i did it by altering the tests locally)
#481

### CODE REVIEW

**Comment by muno92** [comment]
@Summonair 
Thank you!

I run ReSharper locally, and commit inspection result file for testing parser without executing action.

- https://github.com/muno92/resharper_inspectcode/tree/main/__fixtures__/inspection_reports
- https://github.com/muno92/resharper_inspectcode/blob/main/__tests__/report.test.ts

**Comment by Summonair** [comment]
Hey after 2 months of problems with resharper 2024.x, and testing multiple gh actions, i came back here and FINALLY found the problem!!! apparently they moved Severity from issueType to Issue itself on the 2024.x update, its undocumented..
i didnt beyond between alot of versions, and found out that the comparison of 2023.3.6 and 2024.1.0 introduced this problem

this PR fixes this issue #481 
@muno92

**Comment by Summonair** [comment]
For example, on thesame project
**issueType on 2023.3.6** is Severity="WARNING" and there is nothing on the issue itself
**issueType on 2024.1.0** is Severity="DO_NOT_SHOW" - probably for backwards compatibility ,while the Issue itself has Severity="WARNING"

**Comment by Summonair** [comment]
in simple words, It respects _.editorconfig_, the issue was that the XML output has changed both in its logic and structure

**Review by Talbalash-legit — APPROVED** [review]

**Comment by Summonair** [comment]
Hey @muno92,
I hope you're doing well! I wanted to follow up on this PR (#487), this fix is really important for anyone using the updated ReSharper versions with GitHub Actions. I’d appreciate your feedback whenever you have a chance to take a look! 😊

**Comment by muno92** [comment]
@Summonair 

Thank you for the implementation.

However, I couldn't confirm Severity inside Issue with following command.

```bash
jb inspectcode --format=xml --output=report.xml --absolute-paths Your/Solution.sln
```

https://github.com/muno92/resharper_inspectcode/actions/runs/10877669525/job/30179396008

<details>
<summary>2023.3.6</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by JetBrains Inspect Code 2023.3.6 -->
<Report ToolsVersion="233.0.20240606.114341">
  <Information>
    <Solution>/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestSolution.sln</Solution>
    <InspectionScope>
      <Element>Solution</Element>
    </InspectionScope>
  </Information>
  <IssueTypes>
    <IssueType Id="ClassNeverInstantiated.Global" Category="Potential Code Quality Issues" CategoryId="CodeSmell" SubCategory="Class is never instantiated" Description="Class is never instantiated: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/resharperplatform/help?Keyword=ClassNeverInstantiated.Global" />
    <IssueType Id="FieldCanBeMadeReadOnly.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Field can be made readonly" Description="Field can be made readonly: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/resharperplatform/help?Keyword=FieldCanBeMadeReadOnly.Global" />
    <IssueType Id="InconsistentNaming" Category="Constraints Violations" CategoryId="ConstraintViolation" Description="Inconsistent Naming" Severity="WARNING" WikiUrl="https://www.jetbrains.com/resharperplatform/help?Keyword=InconsistentNaming" />
    <IssueType Id="MemberCanBePrivate.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Member can be made private" Description="Member can be made private: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/resharperplatform/help?Keyword=MemberCanBePrivate.Global" />
    <IssueType Id="NotAccessedField.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed field" Severity="WARNING" />
    <IssueType Id="NotAccessedVariable.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed local variable" Severity="WARNING" />
    <IssueType Id="UnusedParameter.Local" Category="Redundancies in Symbol Declarations" CategoryId="DeclarationRedundancy" SubCategory="Unused parameter" Description="Unused parameter: Private accessibility" Severity="WARNING" />
  </IssueTypes>
  <Issues>
    <Project Name="TestConsoleApp">
      <Issue TypeId="ClassNeverInstantiated.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="52-59" Line="5" Message="Class 'Program' is never instantiated" />
      <Issue TypeId="MemberCanBePrivate.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="74-80" Line="7" Message="Field 'canBePrivate' can be made private" />
      <Issue TypeId="FieldCanBeMadeReadOnly.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Field can be made readonly" />
      <Issue TypeId="InconsistentNaming" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Name 'canBePrivate' does not match rule 'Fields (not private)'. Suggested name is 'CanBePrivate'." />
      <Issue TypeId="NotAccessedField.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="147-158" Line="9" Message="Field 'unusedField' is assigned but its value is never used" />
      <Issue TypeId="UnusedParameter.Local" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="199-203" Line="11" Message="Parameter 'args' is never used" />
      <Issue TypeId="NotAccessedVariable.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="231-245" Line="13" Message="Local variable 'unusedVariable' is only assigned but its value is never used" />
    </Project>
  </Issues>
</Report>
```

</details>


<details>
<summary>2024.2</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by JetBrains Inspect Code 2024.2 -->
<Report ToolsVersion="242.0.20240814.114127">
  <Information>
    <Solution>/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestSolution.sln</Solution>
    <InspectionScope>
      <Element>Solution</Element>
    </InspectionScope>
  </Information>
  <IssueTypes>
    <IssueType Id="ClassNeverInstantiated.Global" Category="Potential Code Quality Issues" CategoryId="CodeSmell" SubCategory="Class is never instantiated" Description="Class is never instantiated: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/ClassNeverInstantiated.Global.html" />
    <IssueType Id="FieldCanBeMadeReadOnly.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Field can be made readonly" Description="Field can be made readonly: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/FieldCanBeMadeReadOnly.Global.html" />
    <IssueType Id="InconsistentNaming" Category="Constraints Violations" CategoryId="ConstraintViolation" Description="Inconsistent Naming" Severity="WARNING" WikiUrl="https://www.jetbrains.com/help/resharper/InconsistentNaming.html" />
    <IssueType Id="MemberCanBePrivate.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Member can be made private" Description="Member can be made private: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/MemberCanBePrivate.Global.html" />
    <IssueType Id="NotAccessedField.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed field" Severity="WARNING" />
    <IssueType Id="NotAccessedVariable.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed local variable" Severity="WARNING" />
    <IssueType Id="UnusedParameter.Local" Category="Redundancies in Symbol Declarations" CategoryId="DeclarationRedundancy" SubCategory="Unused parameter" Description="Unused parameter: Private accessibility" Severity="WARNING" WikiUrl="https://www.jetbrains.com/help/resharper/UnusedParameter.Local.html" />
  </IssueTypes>
  <Issues>
    <Project Name="TestConsoleApp">
      <Issue TypeId="ClassNeverInstantiated.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="52-59" Line="5" Message="Class 'Program' is never instantiated" />
      <Issue TypeId="MemberCanBePrivate.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="74-80" Line="7" Message="Field 'canBePrivate' can be made private" />
      <Issue TypeId="FieldCanBeMadeReadOnly.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Field can be made readonly" />
      <Issue TypeId="InconsistentNaming" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Name 'canBePrivate' does not match rule 'Static fields (not private)'. Suggested name is 'CanBePrivate'." />
      <Issue TypeId="NotAccessedField.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="147-158" Line="9" Message="Field 'unusedField' is assigned but its value is never used" />
      <Issue TypeId="InconsistentNaming" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="147-158" Line="9" Message="Name 'unusedField' does not match rule 'Static fields (private)'. Suggested name is '_unusedField'." />
      <Issue TypeId="UnusedParameter.Local" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="199-203" Line="11" Message="Parameter 'args' is never used" />
      <Issue TypeId="NotAccessedVariable.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="231-245" Line="13" Message="Local variable 'unusedVariable' is only assigned but its value is never used" />
    </Project>
  </Issues>
</Report>

```

</details>

Could you tell me the command to reproduce it?

**Comment by muno92** [comment]
And I want to keep backward compatibility.
So even if each issues has a severity in the new resharper version, I want this action to work with both the new and old versions.

**Comment by muno92** [comment]
In SARIF format, each issue has severity as `level`.

So, I intend to add SARIF parser and switch parser with ReSharper version.

**Comment by Summonair** [comment]
> @Summonair
> 
> Thank you for the implementation.
> 
> However, I couldn't confirm Severity inside Issue with following command.
> 
> ```shell
> jb inspectcode --format=xml --output=report.xml --absolute-paths Your/Solution.sln
> ```
> 
> https://github.com/muno92/resharper_inspectcode/actions/runs/10877669525/job/30179396008
> 
> 2023.3.6
> 2024.2
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <Report ToolsVersion="242.0.20240814.114127">
>   <Information>
>     <Solution>/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestSolution.sln</Solution>
>     <InspectionScope>
>       <Element>Solution</Element>
>     </InspectionScope>
>   </Information>
>   <IssueTypes>
>     <IssueType Id="ClassNeverInstantiated.Global" Category="Potential Code Quality Issues" CategoryId="CodeSmell" SubCategory="Class is never instantiated" Description="Class is never instantiated: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/ClassNeverInstantiated.Global.html" />
>     <IssueType Id="FieldCanBeMadeReadOnly.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Field can be made readonly" Description="Field can be made readonly: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/FieldCanBeMadeReadOnly.Global.html" />
>     <IssueType Id="InconsistentNaming" Category="Constraints Violations" CategoryId="ConstraintViolation" Description="Inconsistent Naming" Severity="WARNING" WikiUrl="https://www.jetbrains.com/help/resharper/InconsistentNaming.html" />
>     <IssueType Id="MemberCanBePrivate.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Member can be made private" Description="Member can be made private: Non-private accessibility" Severity="SUGGESTION" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/MemberCanBePrivate.Global.html" />
>     <IssueType Id="NotAccessedField.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed field" Severity="WARNING" />
>     <IssueType Id="NotAccessedVariable.Compiler" Category="Compiler Warnings" CategoryId="CompilerWarnings" Description="Non-accessed local variable" Severity="WARNING" />
>     <IssueType Id="UnusedParameter.Local" Category="Redundancies in Symbol Declarations" CategoryId="DeclarationRedundancy" SubCategory="Unused parameter" Description="Unused parameter: Private accessibility" Severity="WARNING" WikiUrl="https://www.jetbrains.com/help/resharper/UnusedParameter.Local.html" />
>   </IssueTypes>
>   <Issues>
>     <Project Name="TestConsoleApp">
>       <Issue TypeId="ClassNeverInstantiated.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="52-59" Line="5" Message="Class 'Program' is never instantiated" />
>       <Issue TypeId="MemberCanBePrivate.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="74-80" Line="7" Message="Field 'canBePrivate' can be made private" />
>       <Issue TypeId="FieldCanBeMadeReadOnly.Global" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Field can be made readonly" />
>       <Issue TypeId="InconsistentNaming" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="95-107" Line="7" Message="Name 'canBePrivate' does not match rule 'Static fields (not private)'. Suggested name is 'CanBePrivate'." />
>       <Issue TypeId="NotAccessedField.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="147-158" Line="9" Message="Field 'unusedField' is assigned but its value is never used" />
>       <Issue TypeId="InconsistentNaming" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="147-158" Line="9" Message="Name 'unusedField' does not match rule 'Static fields (private)'. Suggested name is '_unusedField'." />
>       <Issue TypeId="UnusedParameter.Local" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="199-203" Line="11" Message="Parameter 'args' is never used" />
>       <Issue TypeId="NotAccessedVariable.Compiler" File="/home/runner/work/resharper_inspectcode/resharper_inspectcode/TestSolution/TestConsoleApp/Program.cs" Offset="231-245" Line="13" Message="Local variable 'unusedVariable' is only assigned but its value is never used" />
>     </Project>
>   </Issues>
> </Report>
> ```
> 
> Could you tell me the command to reproduce it?

the command i used is ` jb inspectcode --absolute-paths ./project.sln --verbosity=WARN --severity=WARNING --build --output=result.xml --format=xml`

here is the output:
```<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by JetBrains Inspect Code 2024.2.4 -->
<Report ToolsVersion="242.0.20240905.115624">
  <Information>
    <Solution>/Users/talbalash/giterepos/y-project/project.sln</Solution>
    <InspectionScope>
      <Element>Solution</Element>
    </InspectionScope>
  </Information>
  <IssueTypes>
    <IssueType Id="BadIndent" Category="Formatting" CategoryId="FormattingIssues" SubCategory="Incorrect indent" Description="Incorrect indent: Redundant indent/outdent elsewhere" Severity="DO_NOT_SHOW" WikiUrl="https://www.jetbrains.com/help/resharper/BadIndent.html" />
    <IssueType Id="TypeWithSuspiciousEqualityIsUsedInRecord.Global" Category="Common Practices and Code Improvements" CategoryId="BestPractice" SubCategory="Type with suspicious equality is used in a record" Description="Type with suspicious equality is used in a record: Non-private accessibility" Severity="WARNING" Global="True" WikiUrl="https://www.jetbrains.com/help/resharper/TypeWithSuspiciousEqualityIsUsedInRecord.Global.html" />
  </IssueTypes>
  <Issues>
    <Project Name="y">
      <Issue TypeId="TypeWithSuspiciousEqualityIsUsedInRecord.Global" File="/Users/talbalash/giterepos/y-project/src/y/Application/CustomDashboards/CustomDashboard.cs" Offset="223-231" Line="15" Message="Type with suspicious equality is used as a member of a record type" />
      <Issue TypeId="TypeWithSuspiciousEqualityIsUsedInRecord.Global" File="/Users/talbalash/giterepos/y-project/src/y/Application/CustomDashboards/CustomDashboard.cs" Offset="272-280" Line="16" Message="Type with suspicious equality is used as a member of a record type" />
    </Project>
    <Project Name="y.Shared">
      <Issue TypeId="BadIndent" Severity="WARNING" File="/Users/talbalash/giterepos/y-project/src/y.Shared/Discovery/Event.cs" Offset="410-418" Line="12" Message="Unexpected line indent change" />
    </Project>
  </Issues>
</Report>

**Comment by Summonair** [comment]
also i observed which its not always the case, sometimes it has both severities, and sometime only the issueType..

**Comment by Summonair** [comment]
> In SARIF format, each issue has severity as `level`.
> 
> So, I intend to add SARIF parser and switch parser with ReSharper version

That sounds like the perfect solution, If you're okay with it, would you mind starting with the implementation of the SARIF parser and the parser selection? I'd be happy to continue from there with the parsing itself, as I'd love to follow your approach. This project is essential for me :pray:

**Comment by muno92** [comment]
> the command i used is  jb inspectcode --absolute-paths ./project.sln --verbosity=WARN --severity=WARNING --build --output=result.xml --format=xml
>
> also i observed which its not always the case, sometimes it has both severities, and sometime only the issueType..

Thank you!

I couldn't reproduce. It's incomprehensible...

> That sounds like the perfect solution, If you're okay with it, would you mind starting with the implementation of the SARIF parser and the parser selection? I'd be happy to continue from there with the parsing itself, as I'd love to follow your approach. 

OK, I will start implementation. Wait for a while, please.

> This project is essential for me

I'm happy to hear that!

**Comment by muno92** [comment]
@Summonair 

Hi.

I finished implementation and released version 1.2.0.
https://github.com/muno92/resharper_inspectcode/releases/tag/1.12.0

You can use ReSharper 2024.x and sarif format with `uses: muno92/resharper_inspectcode@v1`.

Best regards.

**Pull request closed without merging**
